config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :trips
  resources :memorizationpages
  resources :memorizationparts
  resources :attendings
  resources :teachers
  resources :classrooms
  resources :students

  get "classrooms/printclass/:id", to: "classrooms#printclass"


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "classrooms#index"
  
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  has_many :students
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :printclass, :edit, :update, :destroy]

  # GET /classrooms
  # GET /classrooms.json
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
  end

  def printclass
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @classroom, notice: 'Classroom was successfully created.' }
        format.json { render :show, status: :created, location: @classroom }
      else
        format.html { render :new }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1
  # PATCH/PUT /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to @classroom, notice: 'Classroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @classroom }
      else
        format.html { render :edit }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: 'Classroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit(:name, :book, :level, :teacher_id)
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_form.html.erb
<%= form_with(model: classroom, local: true) do |form| %>
  <% if classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :book %>
    <%= form.text_field :book %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level %>
  </div>

  <div class="field">
    <%= form.label :teacher_id %>
    <%= form.text_field :teacher_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/classrooms/edit.html.erb
<h1>Editing Classroom</h1>

<%= render 'form', classroom: @classroom %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>

app/views/classrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Classrooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Book</th>
      <th>Level</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= classroom.name %></td>
        <td><%= classroom.book %></td>
        <td><%= classroom.level %></td>
        <td><%= classroom.teacher.name %></td>
        <td><%= link_to 'Show', classroom %></td>
        <td><%# link_to 'Edit', edit_classroom_path(classroom) %></td>
        <td><%# link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classroom', new_classroom_path %>

app/views/classrooms/new.html.erb
<h1>New Classroom</h1>

<%= render 'form', classroom: @classroom %>

<%= link_to 'Back', classrooms_path %>

app/views/classrooms/printclass.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>اسم الحلقة:</strong>
  حلقة <%= @classroom.name %> 
</p>

<p>
  <strong>الكتاب:</strong>
  <%= @classroom.book %>
</p>

<p>
  <strong>مستوى الحلقة:</strong>
  <%= @classroom.level %>
</p>

<p>
  <strong>اسم المدرس:</strong>
  <%= @classroom.teacher.name %>
</p>

<p>
    <a href="#"><button type="button" class="btn btn-primary">طباعة
    </button></a>
  </p>
  


<table class="table">
    <tr>
    </tr>
  <tbody>
    
      <% @classroom.students.each do |t| %>
      <tr>
      <td> رقم الطالب: </br> <p class="h1"><%= t.id %></p></td>
      <td> <p class="h2"><%= t.fname %></p> </br>  <%= @classroom.name %> 
      </td> 

<td>    <%= image_tag("/student-barcode/bcs_S ("+t.id.to_s+").png", :alt => "rss feed") %>
</td>


      <% end %>
  </tbody>
</table>

app/views/classrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>اسم الحلقة:</strong>
  حلقة <%= @classroom.name %> 
</p>

<p>
  <strong>الكتاب:</strong>
  <%= @classroom.book %>
</p>

<p>
  <strong>مستوى الحلقة:</strong>
  <%= @classroom.level %>
</p>

<p>
  <strong>اسم المدرس:</strong>
  <%= @classroom.teacher.name %>
</p>

<p>
<div class="btn btn-primary ">

<%= link_to 'طباعة', controller: "classrooms", action: "printclass", id: @classroom, class: "btn" %> 
</div>

  </p>
  


<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
    <th scope="col">Id</th>
    <th scope="col">الاسم</th>
    <th scope="col">code</th>

    <th scope="col">النقاط</th>
    <th scope="col">الأجزاء</th>
    <th scope="col">الصفحات</th>
    <th scope="col">الدوام</th>
    <th scope="col">عرض</th>
    </tr>
  </thead>
  <tbody>
    
      <% @classroom.students.each do |t| %>
      <tr>
      <th scope="row"> <%= t.id %>  </th> 
      <td> <%= t.fname %>  
      <%= t.lname %>  </td> 

<td>    <%= image_tag("/student-barcode/bcs_S ("+t.id.to_s+").png", :alt => "rss feed") %>
</td>

      <td> <%= t.point %> نقطة </td> 
      <td> <% t.memorizationparts.each do |f| %>
              <%= f.name %> - 
          <% end %> </td>

      <td> <% t.memorizationpages.each do |p| %>
            <%= p.name %> -  
          <% end %> </td>
      <td>  <%# t.attendings.last.day.try %> </td>
      <td>
        
            <%= link_to 'عرض', student_path(t), :class => "btn btn-primary" %>   
        
      </td>
       </tr>
      <% end %>
  </tbody>
</table>