config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :trips
  resources :memorizationpages
  resources :memorizationparts
  resources :attendings
  resources :teachers
  resources :classrooms
  resources :students

  get "classrooms/printclass/:id", to: "classrooms#printclass"


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "classrooms#index"
  
end

app/models/memorizationpart.rb
class Memorizationpart < ApplicationRecord
  has_and_belongs_to_many  :students
end

app/controllers/memorizationparts_controller.rb
class MemorizationpartsController < ApplicationController
  before_action :set_memorizationpart, only: [:show, :edit, :update, :destroy]

  # GET /memorizationparts
  # GET /memorizationparts.json
  def index
    @memorizationparts = Memorizationpart.all
  end

  # GET /memorizationparts/1
  # GET /memorizationparts/1.json
  def show
  end

  # GET /memorizationparts/new
  def new
    @memorizationpart = Memorizationpart.new
  end

  # GET /memorizationparts/1/edit
  def edit
  end

  # POST /memorizationparts
  # POST /memorizationparts.json
  def create
    @memorizationpart = Memorizationpart.new(memorizationpart_params)

    respond_to do |format|
      if @memorizationpart.save
        format.html { redirect_to @memorizationpart, notice: 'Memorizationpart was successfully created.' }
        format.json { render :show, status: :created, location: @memorizationpart }
      else
        format.html { render :new }
        format.json { render json: @memorizationpart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memorizationparts/1
  # PATCH/PUT /memorizationparts/1.json
  def update
    respond_to do |format|
      if @memorizationpart.update(memorizationpart_params)
        format.html { redirect_to @memorizationpart, notice: 'Memorizationpart was successfully updated.' }
        format.json { render :show, status: :ok, location: @memorizationpart }
      else
        format.html { render :edit }
        format.json { render json: @memorizationpart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memorizationparts/1
  # DELETE /memorizationparts/1.json
  def destroy
    @memorizationpart.destroy
    respond_to do |format|
      format.html { redirect_to memorizationparts_url, notice: 'Memorizationpart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memorizationpart
      @memorizationpart = Memorizationpart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memorizationpart_params
      params.require(:memorizationpart).permit(:name, :students_id)
    end
end

app/helpers/memorizationparts_helper.rb
module MemorizationpartsHelper
end

app/views/memorizationparts/_form.html.erb
<%= form_with(model: memorizationpart, local: true) do |form| %>
  <% if memorizationpart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(memorizationpart.errors.count, "error") %> prohibited this memorizationpart from being saved:</h2>

      <ul>
      <% memorizationpart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :students_id %>
    <%= form.text_field :students_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memorizationparts/edit.html.erb
<h1>Editing Memorizationpart</h1>

<%= render 'form', memorizationpart: @memorizationpart %>

<%= link_to 'Show', @memorizationpart %> |
<%= link_to 'Back', memorizationparts_path %>

app/views/memorizationparts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memorizationparts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Students</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memorizationparts.each do |memorizationpart| %>
      <tr>
        <td><%= memorizationpart.name %></td>
        <td><%= memorizationpart.students %></td>
        <td><%= link_to 'Show', memorizationpart %></td>
        <td><%= link_to 'Edit', edit_memorizationpart_path(memorizationpart) %></td>
        <td><%= link_to 'Destroy', memorizationpart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memorizationpart', new_memorizationpart_path %>

app/views/memorizationparts/new.html.erb
<h1>New Memorizationpart</h1>

<%= render 'form', memorizationpart: @memorizationpart %>

<%= link_to 'Back', memorizationparts_path %>

app/views/memorizationparts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @memorizationpart.name %>
</p>

<p>
  <strong>Students:</strong>
  <%= @memorizationpart.students %>
</p>

<%= link_to 'Edit', edit_memorizationpart_path(@memorizationpart) %> |
<%= link_to 'Back', memorizationparts_path %>